//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietPhieuDBs = new HashSet<ChiTietPhieuDB>();
            this.NguyenLieu_MonAn = new HashSet<NguyenLieu_MonAn>();
        }
    
        public string MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public string MaCongDung { get; set; }
        public string MaLoai { get; set; }
        public string CachLam { get; set; }
        public string YeuCau { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuDB> ChiTietPhieuDBs { get; set; }
        public virtual CongDung CongDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguyenLieu_MonAn> NguyenLieu_MonAn { get; set; }
    }
}
