//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDatBan()
        {
            this.ChiTietPhieuDBs = new HashSet<ChiTietPhieuDB>();
        }
    
        public string MaPhieu { get; set; }
        public string MaKhach { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayDung { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuDB> ChiTietPhieuDBs { get; set; }
        public virtual Khach Khach { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
